// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xjxwghcvmrzeuoovamnb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhqeHdnaGN2bXJ6ZXVvb3ZhbW5iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NDkwNDIsImV4cCI6MjA2NjUyNTA0Mn0.ajRXJddLF-oTrP19knDB4eEsg-p33F_wi3MU-Xxly3s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);